# If not running interactively, don't do anything
[ -z "$PS1" ] && return

if [ -d $HOME/config/zsh/zshrc.d ]; then
  for i in $HOME/config/zsh/zshrc.d/*; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
